# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-04 04:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipoInmueble', models.CharField(choices=[('casa', 'Casa'), ('depa', 'Departamento'), ('dupl', 'Dúplex'), ('ofic', 'Oficina'), ('loca', 'Local comercial')], max_length=10)),
                ('antiguedad', models.PositiveSmallIntegerField()),
                ('recamaras', models.PositiveSmallIntegerField()),
                ('estacionamiento', models.PositiveSmallIntegerField()),
                ('banos', models.PositiveSmallIntegerField()),
                ('mediosBanos', models.PositiveSmallIntegerField()),
                ('tipoVenta', models.BooleanField(default=False)),
                ('tipoRenta', models.BooleanField(default=False)),
                ('tipoTraspaso', models.BooleanField(default=False)),
                ('precioVenta', models.FloatField(blank=True)),
                ('precioRenta', models.FloatField(blank=True)),
                ('precioTraspaso', models.FloatField(blank=True)),
                ('metrosConstruidos', models.FloatField()),
                ('metrosTotales', models.FloatField()),
                ('entidad', models.CharField(max_length=30)),
                ('municipio', models.CharField(max_length=30)),
                ('colonia', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=30)),
                ('numExt', models.CharField(max_length=4)),
                ('numInt', models.CharField(blank=True, max_length=4)),
                ('codigoPostal', models.CharField(blank=True, max_length=30)),
                ('mostrarMapa', models.CharField(choices=[('exac', 'Mostrar ubicación exacta'), ('apro', 'Mostrar ubicación aproximada'), ('no', 'No mostrar')], max_length=4)),
                ('servicioGas', models.BooleanField(default=False)),
                ('servicioAire', models.BooleanField(default=False)),
                ('servicioSegu', models.BooleanField(default=False)),
                ('sevicioCale', models.BooleanField(default=False)),
                ('servicioAmu', models.BooleanField(default=False)),
                ('estadoConservacion', models.CharField(choices=[('buen', 'Bueno'), ('malo', 'Malo'), ('remod', 'Para remodelar'), ('vand', 'Vandalizada')], max_length=4)),
                ('avisoDestacado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
