# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_codigo', models.CharField(max_length=10)),
                ('d_asenta', models.CharField(max_length=100)),
                ('d_mnpio', models.CharField(max_length=100)),
                ('c_mnpio', models.CharField(max_length=10)),
                ('c_estado', models.CharField(max_length=10)),
                ('d_estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Localidades',
            },
        ),
    ]
