# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-10 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0002_localidades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidades',
            options={'managed': False},
        ),
    ]
