# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-23 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0003_auto_20180310_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='antiguedad',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
