# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-14 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0004_auto_20180323_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='latitud',
            field=models.CharField(default=1000, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='longitud',
            field=models.CharField(default=10000, max_length=100),
            preserve_default=False,
        ),
    ]
