# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-14 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0005_auto_20180413_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesInmbueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmueble.Inmueble')),
            ],
        ),
    ]
