# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-14 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0006_imagenesinmbueble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='latitud',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='longitud',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
