# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-14 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0007_auto_20180413_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='antiguedad',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='banos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estacionamiento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='mediosBanos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='metrosConstruidos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='metrosTotales',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precioRenta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precioTraspaso',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precioVenta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='recamaras',
            field=models.CharField(max_length=20),
        ),
    ]
