# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-14 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0009_auto_20180414_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='numInt',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
