# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-24 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0012_auto_20180422_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenesinmbueble',
            name='link',
        ),
    ]
