# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-25 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0013_remove_imagenesinmbueble_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesinmbueble',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=18, max_digits=23, null=True),
        ),
    ]
