# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-26 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0015_auto_20180516_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidades',
            options={'managed': True},
        ),
    ]
