# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-26 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0016_auto_20180526_0410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidades',
            options={'managed': False},
        ),
    ]
