# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-26 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telefonos',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='telefonos',
            name='usuario',
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(default=1234567897, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='telefonos',
        ),
    ]
