# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-26 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20180226_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono2',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
